/* eslint-disable react-refresh/only-export-components, react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { useEffect, useState } from 'react'
import { CheckCircle2, Eye, FileText, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import api from '../services/api'
import Title from '../components/Title'
import Loading from '../components/Loading'
import Empty from '../components/Empty'
import Tag from '../components/Tag'
import Modal from '../components/Modal'

export const DEPARTAMENTOS = [{ id: 1, nombre: 'TI' }, { id: 2, nombre: 'RRHH' }, { id: 3, nombre: 'FINANZAS' }, { id: 4, nombre: 'GERENCIA' }, { id: 5, nombre: 'LEGAL' }]
const EMPTY = { titulo: '', descripcion: '', departamentoId: '', nivelConfidencialidad: 'MEDIO', estado: 'BORRADOR', pais: 'PERU' }
const device = { headers: { 'X-Device-Type': 'WEB' } }

export default function Documents({ puede, onError, onSuccess }) {
  const [docs, setDocs] = useState([]); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState(null); const [editing, setEditing] = useState(null); const [query, setQuery] = useState('')
  const load = async () => { setLoading(true); try { const { data } = await api.get('/api/documentos', device); setDocs(data) } catch (error) { onError(error) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const act = async (type, doc) => { if (type === 'delete' && !window.confirm(`¿Eliminar “${doc.titulo}”?`)) return; try { if (type === 'delete') await api.delete(`/api/documentos/${doc.id}`, device); else await api.put(`/api/documentos/${doc.id}/aprobar`, {}, device); setSelected(null); await load(); onSuccess(type === 'delete' ? 'Documento eliminado.' : 'Documento aprobado.') } catch (error) { onError(error) } }
  const filtered = docs.filter((doc) => `${doc.titulo} ${doc.estado} ${doc.departamento?.nombre}`.toLowerCase().includes(query.toLowerCase()))
  if (editing) return <DocumentForm existing={editing === 'new' ? null : editing} onCancel={() => setEditing(null)} onSaved={async () => { setEditing(null); await load(); onSuccess(editing === 'new' ? 'Documento creado correctamente.' : 'Documento actualizado correctamente.') }} onError={onError} />
  return <div><Title eyebrow="GESTIÓN DOCUMENTAL" title="Documentos" text="Expedientes visibles según tus permisos RBAC y políticas ABAC." action={puede('CREAR_DOCUMENTO') && <button className="btn btn-primary action-button" onClick={() => setEditing('new')}><Plus size={16} /> Nuevo documento</button>} /><div className="toolbar"><div className="search-wrap"><Search size={17} /><input className="form-control search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por título, estado o departamento…" /></div><span className="result-count">{filtered.length} registros visibles</span></div>{loading ? <Loading /> : filtered.length === 0 ? <Empty text="No hay documentos disponibles para tu usuario." /> : <div className="card table-card"><div className="table-responsive"><table className="table align-middle mb-0"><thead><tr><th>DOCUMENTO</th><th>DEPARTAMENTO</th><th>CONFIDENCIALIDAD</th><th>ESTADO</th><th>PAÍS</th><th>ACCIONES</th></tr></thead><tbody>{filtered.map((doc) => <tr key={doc.id}><td><button className="link-button" onClick={() => setSelected(doc)}><span className="document-row-icon"><FileText size={16} /></span><strong>{doc.titulo}</strong></button><small>#{doc.id} · {doc.propietario?.nombre || 'Propietario'}</small></td><td>{doc.departamento?.nombre || '—'}</td><td><Tag text={doc.nivelConfidencialidad} /></td><td><Tag text={doc.estado} tone={doc.estado === 'APROBADO' ? 'green' : 'amber'} /></td><td>{doc.pais || '—'}</td><td><div className="actions"><button className="btn btn-sm btn-light" title="Ver detalle" onClick={() => setSelected(doc)}><Eye size={15} /></button>{puede('MODIFICAR_DOCUMENTO') && <button className="btn btn-sm btn-light" title="Editar" onClick={() => setEditing(doc)}><Pencil size={15} /></button>}{puede('APROBAR_DOCUMENTO') && doc.estado !== 'APROBADO' && <button className="btn btn-sm btn-light text-success" title="Aprobar" onClick={() => act('approve', doc)}><CheckCircle2 size={15} /></button>}{puede('ELIMINAR_DOCUMENTO') && <button className="btn btn-sm btn-light text-danger" title="Eliminar" onClick={() => act('delete', doc)}><Trash2 size={15} /></button>}</div></td></tr>)}</tbody></table></div></div>}{selected && <DocumentDetail doc={selected} onClose={() => setSelected(null)} />}</div>
}

function DocumentForm({ existing, onCancel, onSaved, onError }) { const [form, setForm] = useState(existing ? { titulo: existing.titulo || '', descripcion: existing.descripcion || '', departamentoId: existing.departamento?.id || '', nivelConfidencialidad: existing.nivelConfidencialidad || '', estado: existing.estado || '', pais: existing.pais || '' } : EMPTY); const [saving, setSaving] = useState(false); const update = (key, value) => setForm({ ...form, [key]: value }); const save = async (event) => { event.preventDefault(); setSaving(true); try { const payload = { ...form, departamentoId: Number(form.departamentoId) }; if (existing) await api.put(`/api/documentos/${existing.id}`, payload, device); else await api.post('/api/documentos', payload, device); await onSaved() } catch (error) { onError(error) } finally { setSaving(false) } }; return <div><Title eyebrow="GESTIÓN DOCUMENTAL" title={existing ? 'Editar documento' : 'Nuevo documento'} text="Los atributos serán evaluados por las políticas de acceso." /><form className="card form-card" onSubmit={save}><div className="row g-3"><Field label="Título" value={form.titulo} set={(v) => update('titulo', v)} required /><Field label="País" value={form.pais} set={(v) => update('pais', v)} required /><div className="col-12"><label className="form-label">Descripción<textarea className="form-control" value={form.descripcion} onChange={(event) => update('descripcion', event.target.value)} /></label></div><Select label="Departamento" value={form.departamentoId} set={(v) => update('departamentoId', v)} options={DEPARTAMENTOS.map((department) => ({ value: department.id, label: `${department.nombre} · ID ${department.id}` }))} /><Field label="Nivel de confidencialidad" value={form.nivelConfidencialidad} set={(v) => update('nivelConfidencialidad', v)} required /><Field label="Estado" value={form.estado} set={(v) => update('estado', v)} required /></div><div className="form-actions"><button type="button" className="btn btn-outline-secondary" onClick={onCancel}>Cancelar</button><button className="btn btn-primary" disabled={saving}>{saving ? 'Guardando…' : 'Guardar documento'}</button></div></form></div> }
function Field({ label, value, set, required }) { return <div className="col-md-6"><label className="form-label">{label}<input className="form-control" value={value} onChange={(event) => set(event.target.value)} required={required} /></label></div> }
function Select({ label, value, set, options }) { return <div className="col-md-6"><label className="form-label">{label}<select className="form-select" value={value} onChange={(event) => set(event.target.value)} required><option value="">Selecciona una opción</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label></div> }
function DocumentDetail({ doc, onClose }) { return <Modal onClose={onClose}><span className="eyebrow">DETALLE DEL EXPEDIENTE #{doc.id}</span><h2>{doc.titulo}</h2><p className="text-muted">{doc.descripcion || 'Sin descripción.'}</p><div className="detail-grid">{[['Estado', doc.estado], ['Confidencialidad', doc.nivelConfidencialidad], ['Departamento', doc.departamento?.nombre], ['País', doc.pais], ['Propietario', doc.propietario?.nombre], ['Creado', doc.fechaCreacion ? new Date(doc.fechaCreacion).toLocaleString() : '—']].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value || '—'}</strong></div>)}</div></Modal> }
