import { useState } from 'react'
import { ArrowRight, LockKeyhole, ShieldCheck } from 'lucide-react'
import Brand from '../components/Brand'

export default function Login({ onLogin, onError, toast }) {
  const [form, setForm] = useState({ correo: '', password: '' }); const [loading, setLoading] = useState(false)
  const submit = async (event) => { event.preventDefault(); setLoading(true); try { await onLogin(form) } catch (error) { onError(error) } finally { setLoading(false) } }
  return <div className="login-page"><div className="login-visual"><div className="login-visual-orb"><ShieldCheck size={150} strokeWidth={1} /></div><span className="eyebrow">PLATAFORMA DE CONFIANZA</span><h1>La seguridad también puede ser simple.</h1><p>Gestiona expedientes con acceso basado en roles y políticas contextuales.</p><div className="login-pills"><span><LockKeyhole size={13} /> RBAC</span><span><ShieldCheck size={13} /> ABAC</span><span>JWT</span></div></div><form className="login-card" onSubmit={submit}><Brand /><div className="login-heading"><span className="login-icon"><LockKeyhole size={18} /></span><div><h2>Accede a tu espacio</h2><p className="text-muted">Usa tus credenciales institucionales.</p></div></div><label className="form-label">Correo electrónico<input className="form-control" type="email" value={form.correo} onChange={(event) => setForm({ ...form, correo: event.target.value })} placeholder="nombre@securedocs.com" required /></label><label className="form-label">Contraseña<input className="form-control" type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} placeholder="••••••••" required /></label><button className="btn btn-primary w-100 login-submit" disabled={loading}>{loading ? <><span className="spinner-border spinner-border-sm me-2" />Verificando…</> : <>Iniciar sesión <ArrowRight size={17} /></>}</button>{toast?.type === 'error' && <div className="alert alert-danger mt-3 mb-0">{toast.text}</div>}</form></div>
}
